#!/usr/bin/env bash
# Summary: List all Apache versions that contain the given executable
# Usage: apaenv whence [--path] <command>

set -e
[ -n "$APAENV_DEBUG" ] && set -x

# Provide apaenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec apaenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  apaenv-versions --bare | while read version; do
    path="$(apaenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

APAENV_COMMAND="$1"
if [ -z "$APAENV_COMMAND" ]; then
  apaenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$APAENV_COMMAND")"
[ -n "$result" ] && echo "$result"
