#!/usr/bin/env bash
# Summary: List all Apache versions available to apaenv
# Usage: apaenv versions [--bare]
#
# Lists all Apache versions found in `$APAENV_ROOT/versions/*'.

set -e
[ -n "$APAENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(apaenv-version-name || true)"
  include_system="1"
fi

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(apaenv-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && APAENV_VERSION=system apaenv-which apache >/dev/null 2>&1; then
  print_version system
fi

for path in "${APAENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
