#!/usr/bin/env bash
# Summary: Explain how the current Apache version is set
set -e
[ -n "$APAENV_DEBUG" ] && set -x

if [ -n "$APAENV_VERSION" ]; then
  echo "APAENV_VERSION environment variable"
else
  apaenv-version-file
fi
