#!/usr/bin/env bash
# Summary: Configure the shell environment for apaenv
# Usage: eval "$(apaenv init - [--no-rehash] [<shell>])"

set -e
[ -n "$APAENV_DEBUG" ] && set -x

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "apaenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load apaenv automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo 'eval "$(apaenv init -)"'
    echo
  } >&2

  exit 1
fi

mkdir -p "${APAENV_ROOT}/"{shims,versions}

if [[ ":${PATH}:" != *:"${APAENV_ROOT}/shims":* ]]; then
  echo 'export PATH="'${APAENV_ROOT}'/shims:${PATH}"'
fi

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/apaenv.${shell}\""
  ;;
esac

if [ -z "$no_rehash" ]; then
  echo 'apaenv rehash 2>/dev/null'
fi

commands=(`apaenv-commands --sh`)
IFS="|"
cat <<EOS
apaenv() {
  typeset command
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\`apaenv "sh-\$command" "\$@"\`";;
  *)
    command apaenv "\$command" "\$@";;
  esac
}
EOS
