#!/usr/bin/env bash
# Summary: List existing apaenv shims
# Usage: apaenv shims [--short]

set -e
[ -n "$APAENV_DEBUG" ] && set -x

# Provide apaenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${APAENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
