#!/usr/bin/env bash
# Summary: Show the current Apache version
set -e
[ -n "$APAENV_DEBUG" ] && set -x

if [ -z "$APAENV_VERSION" ]; then
  APAENV_VERSION_FILE="$(apaenv-version-file)"
  APAENV_VERSION="$(apaenv-version-file-read "$APAENV_VERSION_FILE" || true)"
fi

if [ -z "$APAENV_VERSION" ] || [ "$APAENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${APAENV_ROOT}/versions/${version}" ]
}

if version_exists "$APAENV_VERSION"; then
  echo "$APAENV_VERSION"
elif version_exists "${APAENV_VERSION#apache-}"; then
  { echo "warning: ignoring extraneous \`apache-' prefix in version \`${APAENV_VERSION}'"
    echo "         (set by $(apaenv-version-origin))"
  } >&2
  echo "${APAENV_VERSION#apache-}"
else
  echo "apaenv: version \`$APAENV_VERSION' is not installed" >&2
  exit 1
fi
