#!/usr/bin/env bash
# Usage: apaenv completions <command> [arg1 arg2...]

set -e
[ -n "$APAENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  apaenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "apaenv-$COMMAND" || command -v "apaenv-sh-$COMMAND")"
if grep -i "^\([#%]\|--\|//\) provide apaenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
