#!/usr/bin/env bash
# Summary: Start apache in the current folder
# Usage: apaenv start [port]
#
# Start apache in the current folder

set -e
[ -n "$APAENV_DEBUG" ] && set -x

# start apache
apachectl -k stop -f `pwd`/.httpd.conf
