#!/usr/bin/env bash
# Summary: Display prefix for a Apache version
# Usage: apaenv prefix [<version>]
#
# Displays the directory where a Apache version is installed. If no
# version is given, `apaenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$APAENV_DEBUG" ] && set -x

# Provide apaenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec apaenv-versions --bare
fi

if [ -n "$1" ]; then
  export APAENV_VERSION="$1"
elif [ -z "$APAENV_VERSION" ]; then
  APAENV_VERSION="$(apaenv-version-name)"
fi

if [ "$APAENV_VERSION" = "system" ]; then
  APACHE_PATH="$(apaenv-which apache)"
  APACHE_PATH="${APACHE_PATH%/*}"
  echo "${APACHE_PATH%/bin}"
  exit
fi

APAENV_PREFIX_PATH="${APAENV_ROOT}/versions/${APAENV_VERSION}"
if [ ! -d "$APAENV_PREFIX_PATH" ]; then
  echo "apaenv: version \`${APAENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$APAENV_PREFIX_PATH"
