#!/usr/bin/env bash
# Summary: Detect the file that sets the current apaenv version
set -e
[ -n "$APAENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.apache-version" ]; then
      echo "${root}/.apache-version"
      exit
    elif [ -e "${root}/.apaenv-version" ]; then
      echo "${root}/.apaenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$APAENV_DIR"
[ "$APAENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${APAENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${APAENV_ROOT}/global" ]; then
  echo "${APAENV_ROOT}/global"
elif [ -e "${APAENV_ROOT}/default" ]; then
  echo "${APAENV_ROOT}/default"
else
  echo "$global_version_file"
fi
