#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Apache version
#
# Usage: apaenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Apache
# version's `bin' directory is at the front.
#
# For example, if the currently selected Apache version is 0.10.12:
#   apaenv exec npm install
#
# is equivalent to:
#   PATH="$APAENV_ROOT/versions/0.10.12/bin:$PATH" npm install

set -e
[ -n "$APAENV_DEBUG" ] && set -x

# Provide apaenv completions
if [ "$1" = "--complete" ]; then
  exec apaenv shims --short
fi

APAENV_VERSION="$(apaenv-version-name)"
APAENV_COMMAND="$1"

if [ -z "$APAENV_COMMAND" ]; then
  apaenv-help --usage exec >&2
  exit 1
fi

export APAENV_VERSION
APAENV_COMMAND_PATH="$(apaenv-which "$APAENV_COMMAND")"
APAENV_BIN_PATH="${APAENV_COMMAND_PATH%/*}"

OLDIFS="$IFS"
IFS=$'\n' scripts=(`apaenv-hooks exec`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

shift 1
if [ "$APAENV_VERSION" != "system" ]; then
  export PATH="${APAENV_BIN_PATH}:${PATH}"
fi
exec -a "$APAENV_COMMAND" "$APAENV_COMMAND_PATH" "$@"
